[package]
name = "mc-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-anvil = "0.3.3"
image = "0.24.2"
bevy = { version = "0.7.0" }
bevy_egui = "0.14.0"
futures-lite = "1.12.0"